/**
 * Synchronous code generators that produce code snippets from FetchXML.
 *
 * All generators here are pure functions that run locally — no API calls required.
 * For async generators (C# QueryExpression, SQL), see pptbClient.ts.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Format registry
// ─────────────────────────────────────────────────────────────────────────────

export type FxsSyncFormat = "csharp-fetchexpr" | "javascript" | "pac" | "powerautomate" | "webapi";

export const FXS_SYNC_FORMAT_LABELS: Record<FxsSyncFormat, string> = {
	"csharp-fetchexpr": "C# FetchExpression",
	javascript: "JavaScript",
	pac: "pac CLI",
	powerautomate: "Power Automate",
	webapi: "Web API",
};

/** Monaco editor language IDs for each sync format (powerautomate is rendered as a custom UI, not Monaco) */
export const FXS_SYNC_FORMAT_LANG: Record<FxsSyncFormat, string> = {
	"csharp-fetchexpr": "csharp",
	javascript: "javascript",
	pac: "shell",
	powerautomate: "xml", // unused by CodePanel but kept for completeness
	webapi: "plaintext",
};

/**
 * Generate a code snippet for the given sync format.
 * @param fmt           The output format key.
 * @param fetchXml      The FetchXML query string.
 * @param entitySetName Optional OData entity set name (plural, e.g. "accounts"). Used by webapi format.
 * @param orgUrl        Optional org URL (e.g. "https://org.crm.dynamics.com"). Used by webapi format.
 */
export function generateFxsSyncCode(
	fmt: FxsSyncFormat,
	fetchXml: string,
	entitySetName?: string,
	orgUrl?: string,
): string {
	switch (fmt) {
		case "csharp-fetchexpr":
			return generateCSharpFetchExpression(fetchXml);
		case "javascript":
			return generateJavaScript(fetchXml);
		case "pac":
			return generatePacCli(fetchXml);
		case "powerautomate":
			// Power Automate is rendered via PowerAutomatePane (a form UI), not Monaco.
			// This text fallback is used only when plain-text export is needed.
			return fetchXml.trim();
		case "webapi":
			return generateWebApi(fetchXml, orgUrl, entitySetName);
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// C# FetchExpression
// ─────────────────────────────────────────────────────────────────────────────

function generateCSharpFetchExpression(fetchXml: string): string {
	const escaped = fetchXml.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
	// Format as a C# verbatim string if the XML is multi-line, else inline
	const isMultiLine = fetchXml.includes("\n");
	const xmlLiteral = isMultiLine ? `@"\n${fetchXml.replace(/"/g, '""')}\n"` : `"${escaped}"`;

	return [
		"// Generated by FetchXML Studio — Code Generation Panel",
		"// Requires: Microsoft.PowerPlatform.Dataverse.Client or Microsoft.CrmSdk.CoreAssemblies",
		"",
		`var fetchXml = ${xmlLiteral};`,
		"",
		"var query = new FetchExpression(fetchXml);",
		"var results = service.RetrieveMultiple(query);",
		"",
		"foreach (var entity in results.Entities)",
		"{",
		'    // Access attributes: entity["attributename"]',
		"}",
	].join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// JavaScript (Xrm.WebApi)
// ─────────────────────────────────────────────────────────────────────────────

function generateJavaScript(fetchXml: string): string {
	// Extract entity name from FetchXML for the JS snippet
	const entityNameMatch = fetchXml.match(/<fetch[^>]*>[\s\S]*?<entity\s+name=["']([^"']+)["']/i);
	const entityLogicalName = entityNameMatch ? entityNameMatch[1] : "entity_logical_name";

	const encodedXml = encodeForJsTemplate(fetchXml);

	return [
		"// Generated by FetchXML Studio — Code Generation Panel",
		"// Works in Power Apps model-driven app JS / PCF / Dataverse WebAPI",
		"",
		`const fetchXml = \`${encodedXml}\`;`,
		"",
		`Xrm.WebApi.retrieveMultipleRecords("${entityLogicalName}", "?fetchXml=" + encodeURIComponent(fetchXml))`,
		"    .then(function (result) {",
		"        result.entities.forEach(function (record) {",
		'            // Access: record["attribute_name"]',
		"        });",
		"    })",
		"    .catch(function (error) {",
		"        console.error(error.message);",
		"    });",
	].join("\n");
}

/** Escapes backticks and ${} for embedding in a JS template literal */
function encodeForJsTemplate(xml: string): string {
	return xml.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

// ─────────────────────────────────────────────────────────────────────────────
// pac CLI
// ─────────────────────────────────────────────────────────────────────────────

function generatePacCli(fetchXml: string): string {
	// pac expects the XML on one line; collapse whitespace between tags
	const singleLine = fetchXml
		.replace(/>\s+</g, "><")
		.replace(/\s*\n\s*/g, " ")
		.trim();
	// Escape double quotes for shell
	const escaped = singleLine.replace(/"/g, '\\"');

	return [
		"# Generated by FetchXML Studio — Code Generation Panel",
		"# Requires: Power Platform CLI (pac)",
		"# Docs: https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/org#pac-org-fetch",
		"",
		`pac org fetch --xml "${escaped}"`,
	].join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Power Automate — structured field spec (consumed by PowerAutomatePane)
// ─────────────────────────────────────────────────────────────────────────────

/** A single field in the Power Automate connector action form */
export interface PowerAutomateField {
	/** Label mirroring the Power Automate connector UI */
	label: string;
	/** Value ready to paste into that field */
	value: string;
	/** Hint shown below the input */
	hint?: string;
	/** Use a Textarea instead of Input (for multi-line values like FetchXML) */
	multiline?: boolean;
}

export interface PowerAutomateActionSpec {
	/** Display title — e.g. "List rows" */
	actionName: string;
	/** Connector context — e.g. "Microsoft Dataverse connector" */
	connector: string;
	/** Banner shown above the fields */
	banner?: string;
	fields: PowerAutomateField[];
	/** Bulleted notes under the fields */
	notes?: string[];
}

/**
 * Generates a Power Automate "List rows" action spec from a FetchXML query.
 * The FetchXML goes into the "Fetch Xml Query" field; all OData fields are empty.
 */
export function generatePowerAutomateSpec(
	fetchXml: string,
	entitySetName?: string,
): PowerAutomateActionSpec {
	const derivedEntitySet = entitySetName ?? deriveEntitySetName(fetchXml);
	// Extract top/count attribute if present
	const topMatch =
		fetchXml.match(/\bcount=["'](\d+)["']/i) ?? fetchXml.match(/\btop=["'](\d+)["']/i);
	const topCount = topMatch ? topMatch[1] : "";

	return {
		actionName: "List rows",
		connector: "Microsoft Dataverse connector",
		banner:
			'Open the "List rows" action → Show advanced options → paste the FetchXML into the "Fetch Xml Query" field. Leave the OData fields (Select Columns, Filter Rows, Sort By, Expand Query) empty when using FetchXML.',
		fields: [
			{
				label: "Table name",
				value: derivedEntitySet,
				hint: "Entity set name — plural (e.g. accounts, contacts)",
			},
			{
				label: "Select Columns",
				value: "",
				hint: "Leave empty — FetchXML controls column selection",
			},
			{
				label: "Filter Rows",
				value: "",
				hint: "Leave empty — FetchXML controls filtering",
			},
			{
				label: "Sort By",
				value: "",
				hint: "Leave empty — FetchXML controls ordering",
			},
			{
				label: "Top Count",
				value: topCount,
				hint: "Optional total rows cap (extracted from FetchXML count/top attribute)",
			},
			{
				label: "Fetch Xml Query",
				value: fetchXml.trim(),
				hint: 'Paste this into the "Fetch Xml Query" field (Show advanced options)',
				multiline: true,
			},
		],
		notes: [
			"Fetch Xml Query is mutually exclusive with Select Columns / Filter Rows / Sort By — leave those empty.",
			"Maximum Pagination Size enables auto-iteration of pages — set it if you need all rows without a Top Count.",
			"The Table name must be the entity set name (plural), not the logical name.",
		],
	};
}

// ─────────────────────────────────────────────────────────────────────────────
// Web API (OData URL + cURL + PowerShell)
// ─────────────────────────────────────────────────────────────────────────────

function generateWebApi(fetchXml: string, orgUrl?: string, entitySetName?: string): string {
	// Derive entity set name if not provided
	const derivedEntitySet = entitySetName ?? deriveEntitySetName(fetchXml);
	const baseUrl = orgUrl ? orgUrl.replace(/\/$/, "") : "https://<your-org>.crm.dynamics.com";
	const apiPath = `/api/data/v9.2/${derivedEntitySet}`;

	// Compress XML for URL (collapse whitespace)
	const compressedXml = fetchXml
		.replace(/>\s+</g, "><")
		.replace(/\s*\n\s*/g, " ")
		.trim();
	const encodedXml = encodeURIComponent(compressedXml);
	const fullUrl = `${baseUrl}${apiPath}?fetchXml=${encodedXml}`;

	return [
		"// Generated by FetchXML Studio — Code Generation Panel",
		"",
		"// ─── OData URL ───────────────────────────────────────────────────────────────",
		`GET ${baseUrl}${apiPath}?fetchXml=<url-encoded-xml>`,
		"",
		"// Full URL (with encoded FetchXML):",
		fullUrl,
		"",
		"// ─── Required Headers ────────────────────────────────────────────────────────",
		"OData-MaxVersion: 4.0",
		"OData-Version: 4.0",
		"Accept: application/json",
		"Content-Type: application/json; charset=utf-8",
		"Authorization: Bearer <your-access-token>",
		"",
		"// ─── cURL ────────────────────────────────────────────────────────────────────",
		`curl -X GET \\`,
		`  "${fullUrl}" \\`,
		`  -H "OData-MaxVersion: 4.0" \\`,
		`  -H "OData-Version: 4.0" \\`,
		`  -H "Accept: application/json" \\`,
		`  -H "Authorization: Bearer <your-access-token>"`,
		"",
		"// ─── PowerShell ──────────────────────────────────────────────────────────────",
		"$headers = @{",
		'    "OData-MaxVersion" = "4.0"',
		'    "OData-Version"    = "4.0"',
		'    "Accept"           = "application/json"',
		'    "Authorization"    = "Bearer <your-access-token>"',
		"}",
		`$url = "${fullUrl}"`,
		"$response = Invoke-RestMethod -Method Get -Uri $url -Headers $headers",
		"$response.value",
	].join("\n");
}

/**
 * Heuristically derives the OData entity set name (plural) from FetchXML.
 * Falls back to `<logicalName>s` if the entity name cannot be determined.
 */
function deriveEntitySetName(fetchXml: string): string {
	const match = fetchXml.match(/<entity\s+name=["']([^"']+)["']/i);
	if (!match) return "records";
	const logicalName = match[1];

	// Common irregular plurals in Dataverse
	const irregulars: Record<string, string> = {
		opportunity: "opportunities",
		activity: "activities",
		category: "categories",
		territory: "territories",
		currency: "transactioncurrencies",
		systemuser: "systemusers",
		businessunit: "businessunits",
		team: "teams",
	};
	return irregulars[logicalName] ?? `${logicalName}s`;
}
