/**
 * Generates C# SDK QueryExpression code from a Dataverse JSON QueryExpression object.
 *
 * The JSON object is the value of the `Query` property returned by the
 * FetchXmlToQueryExpression Web API function.
 *
 * Generated code targets:
 *   Microsoft.Xrm.Sdk.Query (QueryExpression, ColumnSet, FilterExpression,
 *   ConditionExpression, LinkEntity, OrderExpression, XrmAttributeExpression)
 */

import {
	type QeQueryExpression,
	type QeColumnSet,
	type QeFilterExpression,
	type QeConditionExpression,
	type QeLinkEntity,
	type QeAnyAllFilterLinkEntity,
	type QeOrderExpression,
	LOGICAL_OPERATOR,
	JOIN_OPERATOR,
	ORDER_TYPE,
	CONDITION_OPERATOR,
	XRM_AGGREGATE_TYPE,
	XRM_DATETIME_GROUPING,
} from "./queryExpressionTypes";

// ─────────────────────────────────────────────────────────────────────────────
// Public entry point
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Converts a Dataverse QueryExpression JSON object to C# SDK source code.
 * @param qe  The parsed QueryExpression (from `FetchXmlToQueryExpression().Query`).
 * @returns   C# code string using `Microsoft.Xrm.Sdk.Query` types.
 */
export function generateCSharpQueryExpression(qe: QeQueryExpression): string {
	const lines: string[] = [
		"// Generated by FetchXML Studio — Code Generation Panel",
		"// Requires: Microsoft.PowerPlatform.Dataverse.Client or Microsoft.CrmSdk.CoreAssemblies",
		"",
		`var query = new QueryExpression("${qe.EntityName}")`,
		"{",
	];

	// ColumnSet
	lines.push(...indent(emitColumnSet(qe.ColumnSet)));

	// Criteria
	if (qe.Criteria && hasFilterContent(qe.Criteria)) {
		lines.push(...indent(emitCriteriaProperty(qe.Criteria)));
	}

	// LinkEntities
	if (qe.LinkEntities && qe.LinkEntities.length > 0) {
		lines.push(...indent(emitLinkEntitiesProperty(qe.LinkEntities)));
	}

	// Orders
	if (qe.Orders && qe.Orders.length > 0) {
		lines.push(...indent(emitOrdersProperty(qe.Orders)));
	}

	// TopCount
	if (qe.TopCount != null) {
		lines.push(`    TopCount = ${qe.TopCount},`);
	}

	// Distinct
	if (qe.Distinct) {
		lines.push("    Distinct = true,");
	}

	// NoLock
	if (qe.NoLock) {
		lines.push("    NoLock = true,");
	}

	// PageInfo
	if (qe.PageInfo) {
		const p = qe.PageInfo;
		lines.push("    PageInfo = new PagingInfo");
		lines.push("    {");
		if (p.Count != null) lines.push(`        Count = ${p.Count},`);
		if (p.PageNumber != null) lines.push(`        PageNumber = ${p.PageNumber},`);
		if (p.ReturnTotalRecordCount) lines.push("        ReturnTotalRecordCount = true,");
		lines.push("    },");
	}

	lines.push("};");
	return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// ColumnSet
// ─────────────────────────────────────────────────────────────────────────────

function emitColumnSet(cs: QeColumnSet): string[] {
	// Aggregate query: uses AttributeExpressions
	if (cs.AttributeExpressions && cs.AttributeExpressions.length > 0) {
		const lines: string[] = ["ColumnSet = new ColumnSet(false)"];
		lines.push("{");
		lines.push("    AttributeExpressions =");
		lines.push("    {");
		for (const ae of cs.AttributeExpressions) {
			const aggType = resolveEnum(ae.AggregateType ?? 0, XRM_AGGREGATE_TYPE, "None");
			const isNonTrivialGrouping =
				ae.DateTimeGrouping != null && ae.DateTimeGrouping !== 0 && ae.DateTimeGrouping !== "None";
			const dtGrouping = isNonTrivialGrouping
				? `, XrmDateTimeGrouping.${resolveEnum(ae.DateTimeGrouping!, XRM_DATETIME_GROUPING, "None")}`
				: "";
			const alias = ae.Alias ? `, "${ae.Alias}"` : "";
			const hasGroupBy = ae.HasGroupBy ? ", hasGroupBy: true" : "";
			lines.push(
				`        new XrmAttributeExpression("${ae.AttributeName}", XrmAggregateType.${aggType}${alias}${dtGrouping}${hasGroupBy}),`,
			);
		}
		lines.push("    },");
		lines.push("},");
		return lines;
	}

	// Standard query
	if (cs.AllColumns) {
		return ["ColumnSet = new ColumnSet(true),"];
	}
	if (!cs.Columns || cs.Columns.length === 0) {
		return ["ColumnSet = new ColumnSet(false),"];
	}
	const cols = cs.Columns.map((c) => `"${c}"`).join(", ");
	return [`ColumnSet = new ColumnSet(${cols}),`];
}

// ─────────────────────────────────────────────────────────────────────────────
// FilterExpression
// ─────────────────────────────────────────────────────────────────────────────

function emitCriteriaProperty(filter: QeFilterExpression): string[] {
	const lines: string[] = ["Criteria ="];
	lines.push(...emitFilter(filter));
	// Remove trailing comma from last line of filter and add comma for property assignment
	adjustTrailingComma(lines, true);
	return lines;
}

/**
 * Emits a FilterExpression block (without "= new" assignment — just the value).
 */
function emitFilter(filter: QeFilterExpression, depth = 0): string[] {
	const op = resolveEnum(filter.FilterOperator, LOGICAL_OPERATOR, "And");
	const lines: string[] = [];

	lines.push(`new FilterExpression(LogicalOperator.${op})`);
	lines.push("{");

	const hasConditions = filter.Conditions && filter.Conditions.length > 0;
	const hasSubFilters = filter.Filters && filter.Filters.length > 0;
	const hasAnyAll = filter.AnyAllFilterLinkEntity != null;

	if (hasConditions) {
		lines.push("    Conditions =");
		lines.push("    {");
		for (const cond of filter.Conditions!) {
			lines.push(...indent(emitCondition(cond), 2));
		}
		lines.push("    },");
	}

	if (hasSubFilters) {
		lines.push("    Filters =");
		lines.push("    {");
		for (const sub of filter.Filters!) {
			const subLines = emitFilter(sub, depth + 1);
			lines.push(...indent(subLines, 2));
			// add trailing comma after sub-filter block if missing
			ensureTrailingComma(lines);
		}
		lines.push("    },");
	}

	if (hasAnyAll) {
		lines.push(...indent(emitAnyAllFilterLinkEntity(filter.AnyAllFilterLinkEntity!)));
	}

	lines.push("}");
	return lines;
}

function emitCondition(cond: QeConditionExpression): string[] {
	const opName = resolveEnum(
		cond.Operator,
		CONDITION_OPERATOR,
		`/* ConditionOperator(${cond.Operator}) */`,
	);
	const entityPrefix = cond.EntityName ? `"${cond.EntityName}", ` : "";

	// Sets of operator names and codes that take no values
	const noValueOpNames = new Set(["Null", "NotNull"]);
	const noValueOpCodes = new Set([12, 13]);
	const dateRelativeOpNames = new Set([
		"Yesterday",
		"Today",
		"Tomorrow",
		"Last7Days",
		"Next7Days",
		"LastWeek",
		"ThisWeek",
		"NextWeek",
		"LastMonth",
		"ThisMonth",
		"NextMonth",
		"LastYear",
		"ThisYear",
		"NextYear",
		"EqualUserId",
		"NotEqualUserId",
		"EqualBusinessId",
		"NotEqualBusinessId",
		"EqualUserLanguage",
	]);
	const dateRelativeOpCodes = new Set([
		14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 47, 48, 49, 50, 57,
	]);

	const isNoValue =
		noValueOpNames.has(opName) ||
		(typeof cond.Operator === "number" && noValueOpCodes.has(cond.Operator));
	const isDateRelative =
		dateRelativeOpNames.has(opName) ||
		(typeof cond.Operator === "number" && dateRelativeOpCodes.has(cond.Operator));

	const hasValues = cond.Values && cond.Values.length > 0;

	if (isNoValue || isDateRelative || !hasValues) {
		return [
			`new ConditionExpression(${entityPrefix}"${cond.AttributeName}", ConditionOperator.${opName}),`,
		];
	}

	// Multi-value operators (In, NotIn, Between, NotBetween, ContainValues, DoesNotContainValues)
	const multiValueOpNames = new Set([
		"In",
		"NotIn",
		"Between",
		"NotBetween",
		"ContainValues",
		"DoesNotContainValues",
	]);
	const multiValueOpCodes = new Set([8, 9, 10, 11, 71, 72]);
	const isMultiValue =
		multiValueOpNames.has(opName) ||
		(typeof cond.Operator === "number" && multiValueOpCodes.has(cond.Operator));

	const values = cond.Values!;

	// CompareColumns: values are attribute names
	if (cond.CompareColumns) {
		const colArgs = values.map((v) => `"${v}"`).join(", ");
		return [
			`new ConditionExpression(${entityPrefix}"${cond.AttributeName}", ConditionOperator.${opName}, compareColumns: true, ${colArgs}),`,
		];
	}

	if (isMultiValue && values.length > 1) {
		const valArgs = values.map(formatValue).join(", ");
		return [
			`new ConditionExpression(${entityPrefix}"${cond.AttributeName}", ConditionOperator.${opName}, ${valArgs}),`,
		];
	}

	// Single value
	if (values.length === 1) {
		return [
			`new ConditionExpression(${entityPrefix}"${cond.AttributeName}", ConditionOperator.${opName}, ${formatValue(values[0])}),`,
		];
	}

	// Fallback — no value
	return [
		`new ConditionExpression(${entityPrefix}"${cond.AttributeName}", ConditionOperator.${opName}),`,
	];
}

function emitAnyAllFilterLinkEntity(le: QeAnyAllFilterLinkEntity): string[] {
	const joinOp = resolveEnum(le.JoinOperator, JOIN_OPERATOR, "Inner");
	const lines: string[] = [
		"AnyAllFilterLinkEntity = new LinkEntity",
		`    ("${le.LinkFromEntityName}", "${le.LinkToEntityName}", "${le.LinkFromAttributeName}", "${le.LinkToAttributeName}", JoinOperator.${joinOp})`,
		"{",
	];
	if (le.EntityAlias) lines.push(`    EntityAlias = "${le.EntityAlias}",`);
	if (le.Columns) lines.push(...indent(emitColumnSet(le.Columns)));
	if (le.LinkCriteria && hasFilterContent(le.LinkCriteria)) {
		lines.push(...indent(emitCriteriaProperty(le.LinkCriteria)));
	}
	lines.push("},");
	return lines;
}

// ─────────────────────────────────────────────────────────────────────────────
// LinkEntities
// ─────────────────────────────────────────────────────────────────────────────

function emitLinkEntitiesProperty(links: QeLinkEntity[]): string[] {
	const lines: string[] = ["LinkEntities =", "{"];
	for (const le of links) {
		lines.push(...indent(emitLinkEntity(le)));
		ensureTrailingComma(lines);
	}
	lines.push("},");
	return lines;
}

function emitLinkEntity(le: QeLinkEntity): string[] {
	const joinOp = resolveEnum(le.JoinOperator ?? 0, JOIN_OPERATOR, "Inner");
	const lines: string[] = [
		`new LinkEntity("${le.LinkFromEntityName}", "${le.LinkToEntityName}", "${le.LinkFromAttributeName}", "${le.LinkToAttributeName}", JoinOperator.${joinOp})`,
		"{",
	];

	if (le.EntityAlias) lines.push(`    EntityAlias = "${le.EntityAlias}",`);
	if (le.Columns) lines.push(...indent(emitColumnSet(le.Columns)));
	if (le.LinkCriteria && hasFilterContent(le.LinkCriteria)) {
		lines.push(...indent(emitCriteriaProperty(le.LinkCriteria)));
	}
	if (le.LinkEntities && le.LinkEntities.length > 0) {
		lines.push(...indent(emitLinkEntitiesProperty(le.LinkEntities)));
	}
	if (le.Orders && le.Orders.length > 0) {
		lines.push(...indent(emitOrdersProperty(le.Orders)));
	}

	lines.push("}");
	return lines;
}

// ─────────────────────────────────────────────────────────────────────────────
// Orders
// ─────────────────────────────────────────────────────────────────────────────

function emitOrdersProperty(orders: QeOrderExpression[]): string[] {
	const lines: string[] = ["Orders =", "{"];
	for (const o of orders) {
		lines.push(...indent(emitOrder(o)));
	}
	lines.push("},");
	return lines;
}

function emitOrder(o: QeOrderExpression): string[] {
	const orderType = resolveEnum(o.OrderType ?? 0, ORDER_TYPE, "Ascending");
	const entityPrefix = o.EntityName ? `, "${o.EntityName}"` : "";
	const alias = o.Alias ? `, "${o.Alias}"` : "";
	return [
		`new OrderExpression("${o.AttributeName}", OrderType.${orderType}${entityPrefix}${alias}),`,
	];
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Adds 4-space indentation (× depth) to each line */
function indent(lines: string[], depth = 1): string[] {
	const pad = "    ".repeat(depth);
	return lines.map((l) => (l.length > 0 ? pad + l : l));
}

/**
 * Resolves an enum field that the Dataverse API may return as either a numeric
 * value OR a string name (both formats are seen in practice).
 *
 * - If `v` is already a string, it is used directly as the C# enum member name.
 * - If `v` is a number, it is looked up in `map`; on miss the `fallback` is used.
 */
function resolveEnum(
	v: number | string | null | undefined,
	map: Record<number, string>,
	fallback: string,
): string {
	if (v == null) return fallback;
	if (typeof v === "string") return v; // API already sent the name
	return map[v] ?? fallback;
}

/**
 * Unwraps an OData-typed value object such as
 *   { "@odata.type": "#Edm.Int32", "value": 0 }
 * or a plain wrapper { "Value": "0" } that Dataverse sometimes returns
 * inside ConditionExpression.Values.
 */
function unwrapODataValue(v: unknown): unknown {
	if (v === null || v === undefined || typeof v !== "object") return v;
	const obj = v as Record<string, unknown>;
	const nonMetaKeys = Object.keys(obj).filter((k) => !k.startsWith("@"));
	// Standard OData primitive wrapper: { "value": x } or { "@odata.type": "...", "value": x }
	if ("value" in obj && nonMetaKeys.length <= 1) {
		return obj["value"];
	}
	// Capitalised single-key variant: { "Value": x }
	if ("Value" in obj && nonMetaKeys.length <= 1) {
		return obj["Value"];
	}
	// Microsoft serializer pattern: { "Type": "System.Int32", "Value": 0 }
	if ("Value" in obj && "Type" in obj && nonMetaKeys.length === 2) {
		return obj["Value"];
	}
	return v;
}

/** Formats a condition value to a C# literal */
function formatValue(v: unknown): string {
	const unwrapped = unwrapODataValue(v);
	if (unwrapped === null || unwrapped === undefined) return "null";
	if (typeof unwrapped === "boolean") return unwrapped ? "true" : "false";
	if (typeof unwrapped === "number") return String(unwrapped);
	if (typeof unwrapped === "string") {
		// Detect GUID
		if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(unwrapped)) {
			return `new Guid("${unwrapped}")`;
		}
		// If it looks like a number (comes through as a string), render unquoted
		if (/^-?\d+(\.\d+)?$/.test(unwrapped)) return unwrapped;
		return `"${unwrapped.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
	}
	// Nested object that couldn't be unwrapped — emit as comment so generated code stays valid
	return `/* ${JSON.stringify(unwrapped)} */`;
}

function hasFilterContent(f: QeFilterExpression): boolean {
	return (
		(f.Conditions != null && f.Conditions.length > 0) ||
		(f.Filters != null && f.Filters.length > 0) ||
		f.AnyAllFilterLinkEntity != null
	);
}

/** Ensures the last real (non-empty) line ends with a comma */
function ensureTrailingComma(lines: string[]): void {
	for (let i = lines.length - 1; i >= 0; i--) {
		if (lines[i].trim().length > 0) {
			if (!lines[i].endsWith(",")) {
				lines[i] = lines[i] + ",";
			}
			break;
		}
	}
}

/** Sets or removes trailing comma from last non-empty line */
function adjustTrailingComma(lines: string[], add: boolean): void {
	for (let i = lines.length - 1; i >= 0; i--) {
		if (lines[i].trim().length > 0) {
			lines[i] = lines[i].replace(/,\s*$/, "");
			if (add) lines[i] = lines[i] + ",";
			break;
		}
	}
}
